name: quranify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0   # ✅ Untuk API request
  flutter_tts: ^3.8.3   # ✅ Untuk Text-to-Speech Hadist
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  uuid: ^4.3.3  # For generating unique IDs
  hijri: ^3.0.0  # For Hijri date conversion
  intl: ^0.19.0  # For date formatting
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  youtube_player_flutter: ^9.0.0  # For playing YouTube videos
  url_launcher: ^6.2.5  # For launching YouTube app/website
  googleapis: ^13.0.0  # For YouTube API access
  googleapis_auth: ^1.4.1  # For Google API authentication
  flutter_svg: ^2.0.10  # For rendering SVG images
  # AI Dependencies
  google_generative_ai: ^0.4.3  # For Google Gemini AI
  # Temporarily disabled speech_to_text due to compatibility issues
  # Will need to implement manual text input instead of voice
  flutter_markdown: ^0.6.18  # For displaying AI responses

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    # Root folders (untuk mengakses semua subfolder di dalamnya)
    - assets/images/   # ✅ Folder gambar/icon dan subfoldernya
    - assets/audio/    # ✅ Folder audio dan subfoldernya
    - assets/daftarimage/   # ✅ Folder gambar untuk login
    
    # Explicit listing of critical subfolders to ensure proper bundling in release build
    - assets/images/quiz/
    - assets/images/thumbnail/
    - assets/audio/hijaiyah/

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon-launcher.png"
  adaptive_icon_background: "#FFFFFF" # or any color you prefer
  adaptive_icon_foreground: "assets/images/icon-launcher.png"
  remove_alpha_ios: true
